// app/api/admin/menu-upload/route.ts
import { NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { supabaseServer } from "@/lib/supabaseServer";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const EXACT_HEADERS = [
  "Restro Code",
  "Item Code",
  "Item Name",
  "Item Description",
  "Item Category",
  "Menu Type",
  "Item Cuisine",
  "Start Time",
  "End Time",
  "Restro Price",
  "Base Price",
  "GST %",
  "Base Price GST",
  "Selling Price",
  "Menu Type Rank",
  "Status",
  "Menu Item Image",
] as const;

const ALLOWED_STATUSES = [
  "ON",
  "OFF",
  "DELETED",
] as const;

/*
 * MenuItemFormModal.tsx ke same Menu Type options.
 */
const ALLOWED_MENU_TYPES = [
  "Thalis",
  "Combos",
  "Breakfast",
  "Rice And Biryani",
  "Dal and Subzi",
  "Chicken and Mutton",
  "Roti Paratha",
  "Chinese",
  "Pizza and Sandwiches",
  "Fast Food",
  "Burger",
  "Starters and Snacks",
  "Sweets",
  "Beverages",
  "Restro Specials",
  "Bakery",
] as const;

type ExactHeader =
  (typeof EXACT_HEADERS)[number];

type MenuStatus =
  (typeof ALLOWED_STATUSES)[number];

type UploadMode =
  | "single"
  | "multi";

type PreparedRow = {
  rowNumber: number;
  restroCode: number;
  itemCode: string;
  autoGenerated: boolean;

  payload: {
    restro_code: number;
    item_code: string;
    item_name: string;
    item_description: string | null;
    item_category: string | null;
    menu_type: string | null;
    item_cuisine: string | null;
    start_time: string | null;
    end_time: string | null;
    restro_price: number;
    base_price: number;
    gst_percent: number;
    base_price_gst: number;
    selling_price: number;
    menu_type_rank: number | null;
    status: MenuStatus;
    menu_item_image: string | null;
    updated_at: string;
  };
};

type OutletUploadResult = {
  inserted: number;
  updated: number;
  failed: number;
  generatedItemCodes: number;
};

function cleanText(value: unknown) {
  if (
    value === undefined ||
    value === null
  ) {
    return "";
  }

  return String(value).trim();
}

function normalizeHeader(value: unknown) {
  return cleanText(value).replace(
    /^\uFEFF/,
    ""
  );
}

function isDigitsOnly(value: unknown) {
  return /^\d+$/.test(
    cleanText(value)
  );
}

function normalizeUploadMode(
  value: unknown
): UploadMode {
  const raw = cleanText(value)
    .toLowerCase()
    .replace(/[^a-z]/g, "");

  if (
    raw === "multi" ||
    raw === "multiple" ||
    raw === "universal" ||
    raw === "multioutlet"
  ) {
    return "multi";
  }

  /*
   * Purana frontend uploadMode nahi bhejta.
   * Isliye default single rakha gaya hai.
   */
  return "single";
}

function makeCompositeKey(
  restroCode: number,
  itemCode: string
) {
  return `${restroCode}:${itemCode}`;
}

function parseRequiredNumber(
  value: unknown,
  rowNumber: number,
  columnName: string,
  errors: string[]
) {
  const raw = cleanText(value);

  if (!raw) {
    errors.push(
      `Row ${rowNumber}: ${columnName} is required`
    );

    return null;
  }

  const normalized =
    raw.replace(/,/g, "");

  if (
    !/^(?:\d+|\d*\.\d+)$/.test(
      normalized
    )
  ) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be numeric. Received "${raw}"`
    );

    return null;
  }

  const numberValue =
    Number(normalized);

  if (
    !Number.isFinite(numberValue)
  ) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be a valid number`
    );

    return null;
  }

  if (numberValue < 0) {
    errors.push(
      `Row ${rowNumber}: ${columnName} cannot be negative`
    );

    return null;
  }

  return numberValue;
}

function parseOptionalWholeNumber(
  value: unknown,
  rowNumber: number,
  columnName: string,
  errors: string[]
) {
  const raw = cleanText(value);

  if (!raw) {
    return null;
  }

  if (!/^\d+$/.test(raw)) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be a whole number. Received "${raw}"`
    );

    return null;
  }

  const numberValue =
    Number(raw);

  if (
    !Number.isSafeInteger(
      numberValue
    ) ||
    numberValue < 0
  ) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be a valid whole number`
    );

    return null;
  }

  return numberValue;
}

function parseStatus(
  value: unknown,
  rowNumber: number,
  errors: string[]
): MenuStatus | null {
  const status = cleanText(
    value
  ).toUpperCase();

  if (!status) {
    errors.push(
      `Row ${rowNumber}: Status is required`
    );

    return null;
  }

  if (
    !ALLOWED_STATUSES.includes(
      status as MenuStatus
    )
  ) {
    errors.push(
      `Row ${rowNumber}: Status must be ON, OFF or DELETED. Received "${cleanText(
        value
      )}"`
    );

    return null;
  }

  return status as MenuStatus;
}

function parseMenuType(
  value: unknown,
  rowNumber: number,
  errors: string[]
) {
  const raw = cleanText(value);

  if (!raw) {
    return null;
  }

  const matched =
    ALLOWED_MENU_TYPES.find(
      (allowed) =>
        allowed.toLowerCase() ===
        raw.toLowerCase()
    );

  if (!matched) {
    errors.push(
      `Row ${rowNumber}: Invalid Menu Type "${raw}". Allowed values: ${ALLOWED_MENU_TYPES.join(
        ", "
      )}`
    );

    return null;
  }

  return matched;
}

function calculateMenuRank(
  menuType: string | null
) {
  const value = cleanText(
    menuType
  ).toLowerCase();

  if (!value) return null;

  if (value === "breakfast") {
    return 1;
  }

  if (value === "combos") {
    return 2;
  }

  if (value === "thalis") {
    return 3;
  }

  if (
    value ===
    "rice and biryani"
  ) {
    return 4;
  }

  if (
    value ===
    "dal and subzi"
  ) {
    return 5;
  }

  if (
    value ===
    "chicken and mutton"
  ) {
    return 6;
  }

  if (
    value ===
    "roti paratha"
  ) {
    return 7;
  }

  if (value === "chinese") {
    return 8;
  }

  if (
    value ===
    "pizza and sandwiches"
  ) {
    return 9;
  }

  if (value === "fast food") {
    return 10;
  }

  if (value === "burger") {
    return 11;
  }

  if (
    value ===
    "starters and snacks"
  ) {
    return 12;
  }

  if (value === "sweets") {
    return 13;
  }

  if (value === "beverages") {
    return 14;
  }

  if (
    value ===
    "restro specials"
  ) {
    return 15;
  }

  if (value === "bakery") {
    return 16;
  }

  return null;
}

function parseExcelTime(
  value: unknown,
  rowNumber: number,
  columnName: string,
  errors: string[]
) {
  if (
    value === undefined ||
    value === null ||
    cleanText(value) === ""
  ) {
    return null;
  }

  /*
   * Excel time decimal value.
   */
  if (typeof value === "number") {
    if (
      !Number.isFinite(value) ||
      value < 0 ||
      value >= 1
    ) {
      errors.push(
        `Row ${rowNumber}: ${columnName} contains an invalid Excel time`
      );

      return null;
    }

    const totalSeconds =
      Math.round(
        value * 24 * 60 * 60
      );

    const hours = String(
      Math.floor(
        totalSeconds / 3600
      ) % 24
    ).padStart(2, "0");

    const minutes = String(
      Math.floor(
        (totalSeconds % 3600) /
          60
      )
    ).padStart(2, "0");

    const seconds = String(
      totalSeconds % 60
    ).padStart(2, "0");

    return `${hours}:${minutes}:${seconds}`;
  }

  const raw = cleanText(value);

  const match = raw.match(
    /^(\d{1,2}):(\d{2})(?::(\d{2}))?$/
  );

  if (!match) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be HH:MM or HH:MM:SS. Received "${raw}"`
    );

    return null;
  }

  const hours =
    Number(match[1]);

  const minutes =
    Number(match[2]);

  const seconds =
    Number(match[3] ?? "0");

  if (
    hours < 0 ||
    hours > 23 ||
    minutes < 0 ||
    minutes > 59 ||
    seconds < 0 ||
    seconds > 59
  ) {
    errors.push(
      `Row ${rowNumber}: ${columnName} contains an invalid time "${raw}"`
    );

    return null;
  }

  return `${String(
    hours
  ).padStart(2, "0")}:${String(
    minutes
  ).padStart(2, "0")}:${String(
    seconds
  ).padStart(2, "0")}`;
}

function validateHeaders(
  actualHeaders: unknown[]
) {
  const normalizedHeaders =
    actualHeaders.map(
      normalizeHeader
    );

  const errors: string[] = [];

  if (
    normalizedHeaders.length !==
    EXACT_HEADERS.length
  ) {
    errors.push(
      `Header count is incorrect. Expected ${EXACT_HEADERS.length} headers but found ${normalizedHeaders.length}.`
    );
  }

  const maximumLength =
    Math.max(
      normalizedHeaders.length,
      EXACT_HEADERS.length
    );

  for (
    let index = 0;
    index < maximumLength;
    index++
  ) {
    const expected =
      EXACT_HEADERS[index];

    const received =
      normalizedHeaders[index];

    if (expected !== received) {
      errors.push(
        `Column ${index + 1}: Expected header "${expected ?? "none"}" but found "${received ?? "missing"}".`
      );
    }
  }

  const duplicateHeaders =
    normalizedHeaders.filter(
      (header, index) =>
        header &&
        normalizedHeaders.indexOf(
          header
        ) !== index
    );

  if (duplicateHeaders.length) {
    errors.push(
      `Duplicate headers found: ${Array.from(
        new Set(
          duplicateHeaders
        )
      ).join(", ")}`
    );
  }

  return errors;
}

function createRowObject(
  rowValues: unknown[]
) {
  const row = {} as Record<
    ExactHeader,
    unknown
  >;

  EXACT_HEADERS.forEach(
    (header, index) => {
      row[header] =
        rowValues[index] ?? "";
    }
  );

  return row;
}

function isCompletelyBlankRow(
  rowValues: unknown[]
) {
  return rowValues.every(
    (value) =>
      cleanText(value) === ""
  );
}

function getOrCreateOutletResult(
  resultMap: Map<
    number,
    OutletUploadResult
  >,
  restroCode: number
) {
  const existing =
    resultMap.get(restroCode);

  if (existing) {
    return existing;
  }

  const created: OutletUploadResult =
    {
      inserted: 0,
      updated: 0,
      failed: 0,
      generatedItemCodes: 0,
    };

  resultMap.set(
    restroCode,
    created
  );

  return created;
}

export async function POST(
  req: Request
) {
  try {
    const formData =
      await req.formData();

    const uploadMode =
      normalizeUploadMode(
        formData.get("uploadMode")
      );

    const selectedRestroCodeRaw =
      cleanText(
        formData.get("restroCode")
      );

    const file =
      formData.get("file");

    let selectedRestroCode:
      | number
      | null = null;

    /*
     * Single mode me popup wala Restro Code compulsory hai.
     *
     * Multi mode me Restro Codes Excel rows se read honge.
     */
    if (uploadMode === "single") {
      if (
        !isDigitsOnly(
          selectedRestroCodeRaw
        )
      ) {
        return NextResponse.json(
          {
            ok: false,
            error:
              "Restro Code must contain numbers only",
          },
          { status: 400 }
        );
      }

      selectedRestroCode =
        Number(
          selectedRestroCodeRaw
        );

      if (
        !Number.isSafeInteger(
          selectedRestroCode
        ) ||
        selectedRestroCode <= 0
      ) {
        return NextResponse.json(
          {
            ok: false,
            error:
              "Valid Restro Code required",
          },
          { status: 400 }
        );
      }
    }

    if (!(file instanceof File)) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Excel or CSV file required",
        },
        { status: 400 }
      );
    }

    const fileName =
      file.name.toLowerCase();

    if (
      !fileName.endsWith(
        ".xlsx"
      ) &&
      !fileName.endsWith(
        ".xls"
      ) &&
      !fileName.endsWith(
        ".csv"
      )
    ) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Only .xlsx, .xls or .csv file is allowed",
        },
        { status: 400 }
      );
    }

    if (file.size <= 0) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Uploaded file is empty",
        },
        { status: 400 }
      );
    }

    if (
      file.size >
      10 * 1024 * 1024
    ) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Menu file is too large. Maximum allowed size is 10 MB",
        },
        { status: 400 }
      );
    }

    const buffer =
      Buffer.from(
        await file.arrayBuffer()
      );

    let workbook:
      XLSX.WorkBook;

    try {
      workbook = XLSX.read(
        buffer,
        {
          type: "buffer",
          cellDates: false,
          raw: true,
        }
      );
    } catch {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Unable to read the uploaded Excel/CSV file",
        },
        { status: 400 }
      );
    }

    const sheetName =
      workbook.SheetNames[0];

    if (!sheetName) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Excel sheet not found",
        },
        { status: 400 }
      );
    }

    const sheet =
      workbook.Sheets[sheetName];

    const rawRows =
      XLSX.utils.sheet_to_json<
        unknown[]
      >(sheet, {
        header: 1,
        defval: "",
        raw: true,
        blankrows: false,
      });

    if (!rawRows.length) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Excel file is empty",
        },
        { status: 400 }
      );
    }

    const actualHeaders =
      rawRows[0] ?? [];

    const headerErrors =
      validateHeaders(
        actualHeaders
      );

    if (headerErrors.length) {
      return NextResponse.json(
        {
          ok: false,
          error: [
            "Invalid menu file headers.",
            ...headerErrors.slice(
              0,
              20
            ),
            "",
            `Required header order: ${EXACT_HEADERS.join(
              " | "
            )}`,
          ].join("\n"),
        },
        { status: 400 }
      );
    }

    const dataRows = rawRows
      .slice(1)
      .filter(
        (row) =>
          !isCompletelyBlankRow(
            row
          )
      );

    if (!dataRows.length) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "No menu rows found in the file",
        },
        { status: 400 }
      );
    }

    /*
     * First pass:
     *
     * Excel rows ke Restro Codes validate aur collect honge.
     * Is stage par database me koi write nahi hogi.
     */
    const initialValidationErrors:
      string[] = [];

    const targetRestroCodes =
      new Set<number>();

    const rowRestroCodeMap =
      new Map<number, number>();

    for (
      let index = 0;
      index < dataRows.length;
      index++
    ) {
      const rowNumber =
        index + 2;

      const row =
        createRowObject(
          dataRows[index]
        );

      const rowRestroCodeRaw =
        cleanText(
          row["Restro Code"]
        );

      if (!rowRestroCodeRaw) {
        initialValidationErrors.push(
          `Row ${rowNumber}: Restro Code is required`
        );

        continue;
      }

      if (
        !isDigitsOnly(
          rowRestroCodeRaw
        )
      ) {
        initialValidationErrors.push(
          `Row ${rowNumber}: Restro Code must be numeric. Received "${rowRestroCodeRaw}"`
        );

        continue;
      }

      const rowRestroCode =
        Number(
          rowRestroCodeRaw
        );

      if (
        !Number.isSafeInteger(
          rowRestroCode
        ) ||
        rowRestroCode <= 0
      ) {
        initialValidationErrors.push(
          `Row ${rowNumber}: Restro Code is invalid`
        );

        continue;
      }

      if (
        uploadMode === "single" &&
        selectedRestroCode !==
          null &&
        rowRestroCode !==
          selectedRestroCode
      ) {
        initialValidationErrors.push(
          `Row ${rowNumber}: File Restro Code ${rowRestroCode} does not match selected Restro Code ${selectedRestroCode}`
        );

        continue;
      }

      rowRestroCodeMap.set(
        index,
        rowRestroCode
      );

      targetRestroCodes.add(
        rowRestroCode
      );
    }

    if (
      initialValidationErrors.length
    ) {
      const shownErrors =
        initialValidationErrors.slice(
          0,
          50
        );

      const remainingErrors =
        initialValidationErrors.length -
        shownErrors.length;

      return NextResponse.json(
        {
          ok: false,

          error: [
            `Menu file validation failed. ${initialValidationErrors.length} error(s) found. No rows were uploaded.`,
            "",
            ...shownErrors,
            ...(remainingErrors > 0
              ? [
                  "",
                  `And ${remainingErrors} more error(s).`,
                ]
              : []),
          ].join("\n"),

          totalRows:
            dataRows.length,

          validRows:
            dataRows.length -
            initialValidationErrors.length,

          invalidRows:
            initialValidationErrors.length,
        },
        { status: 400 }
      );
    }

    const targetRestroCodeList =
      Array.from(
        targetRestroCodes
      );

    if (
      !targetRestroCodeList.length
    ) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "No valid Restro Codes found in the file",
        },
        { status: 400 }
      );
    }

    /*
     * Excel me diye gaye sabhi Restro Codes
     * RestroMaster me exist hone chahiye.
     */
    const {
      data: restroMasterRows,
      error: restroMasterError,
    } = await supabaseServer
      .from("RestroMaster")
      .select("RestroCode")
      .in(
        "RestroCode",
        targetRestroCodeList
      );

    if (restroMasterError) {
      return NextResponse.json(
        {
          ok: false,
          error:
            restroMasterError.message,
        },
        { status: 500 }
      );
    }

    const existingRestroCodes =
      new Set<number>();

    for (
      const restroRow of
        restroMasterRows ?? []
    ) {
      const code = Number(
        restroRow.RestroCode
      );

      if (
        Number.isSafeInteger(code) &&
        code > 0
      ) {
        existingRestroCodes.add(
          code
        );
      }
    }

    const missingRestroCodes =
      targetRestroCodeList.filter(
        (code) =>
          !existingRestroCodes.has(
            code
          )
      );

    if (
      missingRestroCodes.length
    ) {
      const missingRows:
        string[] = [];

      for (
        let index = 0;
        index < dataRows.length;
        index++
      ) {
        const restroCode =
          rowRestroCodeMap.get(
            index
          );

        if (
          restroCode &&
          missingRestroCodes.includes(
            restroCode
          )
        ) {
          missingRows.push(
            `Row ${index + 2}: Restro Code ${restroCode} does not exist in RestroMaster`
          );
        }
      }

      return NextResponse.json(
        {
          ok: false,

          error: [
            "Menu file validation failed. No rows were uploaded.",
            "",
            ...missingRows.slice(
              0,
              50
            ),
          ].join("\n"),

          missingRestroCodes,
        },
        { status: 400 }
      );
    }

    /*
     * Target outlets ke existing menu rows load honge.
     *
     * Existing item match:
     * Restro Code + Item Code
     */
    const {
      data: existingRows,
      error: existingError,
    } = await supabaseServer
      .from("RestroMenuItems")
      .select(
        "id,restro_code,item_code"
      )
      .in(
        "restro_code",
        targetRestroCodeList
      );

    if (existingError) {
      return NextResponse.json(
        {
          ok: false,
          error:
            existingError.message,
        },
        { status: 500 }
      );
    }

    const existingByCompositeKey =
      new Map<string, number>();

    const usedItemCodesByRestro =
      new Map<
        number,
        Set<string>
      >();

    const maximumItemCodeByRestro =
      new Map<number, number>();

    for (
      const restroCode of
        targetRestroCodeList
    ) {
      usedItemCodesByRestro.set(
        restroCode,
        new Set<string>()
      );

      maximumItemCodeByRestro.set(
        restroCode,
        0
      );
    }

    for (
      const existingRow of
        existingRows ?? []
    ) {
      const existingRestroCode =
        Number(
          existingRow.restro_code
        );

      const existingItemCode =
        cleanText(
          existingRow.item_code
        );

      if (
        !Number.isSafeInteger(
          existingRestroCode
        ) ||
        existingRestroCode <= 0 ||
        !existingItemCode
      ) {
        continue;
      }

      let outletUsedCodes =
        usedItemCodesByRestro.get(
          existingRestroCode
        );

      if (!outletUsedCodes) {
        outletUsedCodes =
          new Set<string>();

        usedItemCodesByRestro.set(
          existingRestroCode,
          outletUsedCodes
        );
      }

      outletUsedCodes.add(
        existingItemCode
      );

      if (existingRow.id) {
        existingByCompositeKey.set(
          makeCompositeKey(
            existingRestroCode,
            existingItemCode
          ),
          Number(existingRow.id)
        );
      }

      if (
        isDigitsOnly(
          existingItemCode
        )
      ) {
        const numericCode =
          Number(
            existingItemCode
          );

        const currentMaximum =
          maximumItemCodeByRestro.get(
            existingRestroCode
          ) ?? 0;

        if (
          Number.isSafeInteger(
            numericCode
          ) &&
          numericCode >
            currentMaximum
        ) {
          maximumItemCodeByRestro.set(
            existingRestroCode,
            numericCode
          );
        }
      }
    }

    /*
     * File me manually diye gaye bade Item Codes ko bhi
     * us outlet ke maximum Item Code me include karenge.
     *
     * Isse blank Item Code ki auto-generation duplicate
     * manual Item Code create nahi karegi.
     */
    for (
      let index = 0;
      index < dataRows.length;
      index++
    ) {
      const restroCode =
        rowRestroCodeMap.get(
          index
        );

      if (!restroCode) {
        continue;
      }

      const row =
        createRowObject(
          dataRows[index]
        );

      const rawItemCode =
        cleanText(
          row["Item Code"]
        );

      if (
        rawItemCode &&
        isDigitsOnly(
          rawItemCode
        )
      ) {
        const numericCode =
          Number(rawItemCode);

        const currentMaximum =
          maximumItemCodeByRestro.get(
            restroCode
          ) ?? 0;

        if (
          Number.isSafeInteger(
            numericCode
          ) &&
          numericCode >
            currentMaximum
        ) {
          maximumItemCodeByRestro.set(
            restroCode,
            numericCode
          );
        }
      }
    }

    const validationErrors:
      string[] = [];

    const preparedRows:
      PreparedRow[] = [];

    /*
     * Duplicate check ab outlet-wise hoga:
     *
     * Restro Code + Item Code
     */
    const fileCompositeKeys =
      new Set<string>();

    let generatedItemCodes = 0;

    /*
     * Pehle complete file validate hogi.
     * Validation ke time koi database write nahi hogi.
     */
    for (
      let index = 0;
      index < dataRows.length;
      index++
    ) {
      const values =
        dataRows[index];

      const rowNumber =
        index + 2;

      const row =
        createRowObject(values);

      const restroCode =
        rowRestroCodeMap.get(
          index
        );

      const errorsBefore =
        validationErrors.length;

      if (!restroCode) {
        validationErrors.push(
          `Row ${rowNumber}: Valid Restro Code is required`
        );

        continue;
      }

      let itemCode =
        cleanText(
          row["Item Code"]
        );

      let autoGenerated = false;

      /*
       * Filled Item Code:
       * numeric hona compulsory hai.
       *
       * Blank Item Code:
       * same outlet ke last existing maximum + 1
       * se generate hoga.
       */
      if (itemCode) {
        if (
          !isDigitsOnly(itemCode)
        ) {
          validationErrors.push(
            `Row ${rowNumber}: Item Code must be numeric or blank. Received "${itemCode}"`
          );
        } else {
          const itemCodeNumber =
            Number(itemCode);

          if (
            !Number.isSafeInteger(
              itemCodeNumber
            ) ||
            itemCodeNumber <= 0
          ) {
            validationErrors.push(
              `Row ${rowNumber}: Item Code must be a positive whole number`
            );
          }

          const compositeKey =
            makeCompositeKey(
              restroCode,
              itemCode
            );

          if (
            fileCompositeKeys.has(
              compositeKey
            )
          ) {
            validationErrors.push(
              `Row ${rowNumber}: Duplicate Restro Code ${restroCode} and Item Code ${itemCode} found in the file`
            );
          } else {
            fileCompositeKeys.add(
              compositeKey
            );
          }
        }
      } else {
        let maximumItemCode =
          maximumItemCodeByRestro.get(
            restroCode
          ) ?? 0;

        let outletUsedCodes =
          usedItemCodesByRestro.get(
            restroCode
          );

        if (!outletUsedCodes) {
          outletUsedCodes =
            new Set<string>();

          usedItemCodesByRestro.set(
            restroCode,
            outletUsedCodes
          );
        }

        do {
          maximumItemCode += 1;

          itemCode =
            String(
              maximumItemCode
            );
        } while (
          outletUsedCodes.has(
            itemCode
          ) ||
          fileCompositeKeys.has(
            makeCompositeKey(
              restroCode,
              itemCode
            )
          )
        );

        maximumItemCodeByRestro.set(
          restroCode,
          maximumItemCode
        );

        autoGenerated = true;
        generatedItemCodes += 1;

        outletUsedCodes.add(
          itemCode
        );

        fileCompositeKeys.add(
          makeCompositeKey(
            restroCode,
            itemCode
          )
        );
      }

      const itemName =
        cleanText(
          row["Item Name"]
        );

      if (!itemName) {
        validationErrors.push(
          `Row ${rowNumber}: Item Name is required`
        );
      }

      const menuType =
        parseMenuType(
          row["Menu Type"],
          rowNumber,
          validationErrors
        );

      const itemCuisine =
        cleanText(
          row["Item Cuisine"]
        );

      const startTime =
        parseExcelTime(
          row["Start Time"],
          rowNumber,
          "Start Time",
          validationErrors
        );

      const endTime =
        parseExcelTime(
          row["End Time"],
          rowNumber,
          "End Time",
          validationErrors
        );

      const restroPrice =
        parseRequiredNumber(
          row["Restro Price"],
          rowNumber,
          "Restro Price",
          validationErrors
        );

      const basePrice =
        parseRequiredNumber(
          row["Base Price"],
          rowNumber,
          "Base Price",
          validationErrors
        );

      const gstPercent =
        parseRequiredNumber(
          row["GST %"],
          rowNumber,
          "GST %",
          validationErrors
        );

      const basePriceGst =
        parseRequiredNumber(
          row["Base Price GST"],
          rowNumber,
          "Base Price GST",
          validationErrors
        );

      const sellingPrice =
        parseRequiredNumber(
          row["Selling Price"],
          rowNumber,
          "Selling Price",
          validationErrors
        );

      if (
        gstPercent !== null &&
        gstPercent > 100
      ) {
        validationErrors.push(
          `Row ${rowNumber}: GST % cannot be greater than 100`
        );
      }

      const uploadedMenuTypeRank =
        parseOptionalWholeNumber(
          row["Menu Type Rank"],
          rowNumber,
          "Menu Type Rank",
          validationErrors
        );

      const finalMenuTypeRank =
        uploadedMenuTypeRank ??
        calculateMenuRank(
          menuType
        );

      const status =
        parseStatus(
          row["Status"],
          rowNumber,
          validationErrors
        );

      if (
        validationErrors.length >
        errorsBefore
      ) {
        continue;
      }

      if (
        restroPrice === null ||
        basePrice === null ||
        gstPercent === null ||
        basePriceGst === null ||
        sellingPrice === null ||
        status === null
      ) {
        continue;
      }

      preparedRows.push({
        rowNumber,
        restroCode,
        itemCode,
        autoGenerated,

        payload: {
          restro_code:
            restroCode,

          item_code:
            itemCode,

          item_name:
            itemName,

          item_description:
            cleanText(
              row[
                "Item Description"
              ]
            ) || null,

          item_category:
            cleanText(
              row[
                "Item Category"
              ]
            ) || null,

          menu_type:
            menuType,

          item_cuisine:
            itemCuisine || null,

          start_time:
            startTime,

          end_time:
            endTime,

          restro_price:
            restroPrice,

          base_price:
            basePrice,

          gst_percent:
            gstPercent,

          base_price_gst:
            basePriceGst,

          selling_price:
            sellingPrice,

          menu_type_rank:
            finalMenuTypeRank,

          status,

          menu_item_image:
            cleanText(
              row[
                "Menu Item Image"
              ]
            ) || null,

          updated_at:
            new Date().toISOString(),
        },
      });
    }

    /*
     * Ek bhi validation error hua to koi row save nahi hogi.
     */
    if (
      validationErrors.length
    ) {
      const shownErrors =
        validationErrors.slice(
          0,
          50
        );

      const remainingErrors =
        validationErrors.length -
        shownErrors.length;

      return NextResponse.json(
        {
          ok: false,

          error: [
            `Menu file validation failed. ${validationErrors.length} error(s) found. No rows were uploaded.`,
            "",
            ...shownErrors,
            ...(remainingErrors > 0
              ? [
                  "",
                  `And ${remainingErrors} more error(s).`,
                ]
              : []),
          ].join("\n"),

          totalRows:
            dataRows.length,

          validRows:
            preparedRows.length,

          invalidRows:
            dataRows.length -
            preparedRows.length,
        },
        { status: 400 }
      );
    }

    let inserted = 0;
    let updated = 0;

    const databaseErrors:
      string[] = [];

    const outletResults =
      new Map<
        number,
        OutletUploadResult
      >();

    /*
     * Validated rows save hongi.
     *
     * Item Code present + same Restro Code match:
     * existing row UPDATE.
     *
     * Item Code blank tha:
     * generated code ke saath INSERT.
     */
    for (
      const preparedRow of
        preparedRows
    ) {
      const compositeKey =
        makeCompositeKey(
          preparedRow.restroCode,
          preparedRow.itemCode
        );

      const existingId =
        existingByCompositeKey.get(
          compositeKey
        );

      const outletResult =
        getOrCreateOutletResult(
          outletResults,
          preparedRow.restroCode
        );

      if (
        preparedRow.autoGenerated
      ) {
        outletResult.generatedItemCodes +=
          1;
      }

      if (existingId) {
        const { error } =
          await supabaseServer
            .from(
              "RestroMenuItems"
            )
            .update(
              preparedRow.payload
            )
            .eq(
              "id",
              existingId
            )
            .eq(
              "restro_code",
              preparedRow.restroCode
            )
            .eq(
              "item_code",
              preparedRow.itemCode
            );

        if (error) {
          databaseErrors.push(
            `Row ${preparedRow.rowNumber} | Restro ${preparedRow.restroCode} | Item ${preparedRow.itemCode}: ${error.message}`
          );

          outletResult.failed += 1;
        } else {
          updated += 1;
          outletResult.updated += 1;
        }
      } else {
        const { data, error } =
          await supabaseServer
            .from(
              "RestroMenuItems"
            )
            .insert({
              ...preparedRow.payload,

              created_at:
                new Date().toISOString(),
            })
            .select(
              "id,restro_code,item_code"
            )
            .single();

        if (error) {
          databaseErrors.push(
            `Row ${preparedRow.rowNumber} | Restro ${preparedRow.restroCode} | Item ${preparedRow.itemCode}: ${error.message}`
          );

          outletResult.failed += 1;
        } else {
          inserted += 1;
          outletResult.inserted += 1;

          if (data?.id) {
            existingByCompositeKey.set(
              compositeKey,
              Number(data.id)
            );
          }
        }
      }
    }

    const outletResultLines =
      Array.from(
        outletResults.entries()
      )
        .sort(
          ([codeA], [codeB]) =>
            codeA - codeB
        )
        .map(
          ([
            restroCode,
            result,
          ]) => {
            const parts = [
              `Restro ${restroCode}`,
              `Inserted: ${result.inserted}`,
              `Updated: ${result.updated}`,
            ];

            if (
              result.generatedItemCodes >
              0
            ) {
              parts.push(
                `Generated Codes: ${result.generatedItemCodes}`
              );
            }

            if (
              result.failed > 0
            ) {
              parts.push(
                `Failed: ${result.failed}`
              );
            }

            return parts.join(
              " | "
            );
          }
        );

    if (
      databaseErrors.length
    ) {
      return NextResponse.json(
        {
          ok: false,

          error: [
            "Menu data was valid, but some database rows could not be saved.",
            "",
            ...databaseErrors.slice(
              0,
              30
            ),
          ].join("\n"),

          uploadMode,

          totalOutlets:
            targetRestroCodeList.length,

          totalRows:
            preparedRows.length,

          inserted,
          updated,

          generatedItemCodes,

          failed:
            databaseErrors.length,

          outletResults:
            Object.fromEntries(
              outletResults
            ),
        },
        { status: 500 }
      );
    }

    return NextResponse.json({
      ok: true,

      uploadMode,

      inserted,
      updated,

      generatedItemCodes,

      totalRows:
        preparedRows.length,

      totalOutlets:
        targetRestroCodeList.length,

      outletResults:
        Object.fromEntries(
          outletResults
        ),

      message: [
        "Menu Upload Successful",
        "",
        `Upload Mode: ${
          uploadMode === "multi"
            ? "Multiple Outlets"
            : "Single Outlet"
        }`,
        `Total Outlets: ${targetRestroCodeList.length}`,
        `Total Rows: ${preparedRows.length}`,
        `Inserted: ${inserted}`,
        `Updated: ${updated}`,
        `Generated Item Codes: ${generatedItemCodes}`,
        "",
        ...outletResultLines,
      ].join("\n"),
    });
  } catch (error: any) {
    return NextResponse.json(
      {
        ok: false,

        error:
          error?.message ||
          "Menu upload failed",
      },
      { status: 500 }
    );
  }
}
