// app/api/admin/menu-upload/route.ts
import { NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { supabaseServer } from "@/lib/supabaseServer";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const EXACT_HEADERS = [
  "Restro Code",
  "Item Code",
  "Item Name",
  "Item Description",
  "Item Category",
  "Menu Type",
  "Item Cuisine",
  "Start Time",
  "End Time",
  "Restro Price",
  "Base Price",
  "GST %",
  "Base Price GST",
  "Selling Price",
  "Menu Type Rank",
  "Status",
  "Menu Item Image",
] as const;

const ALLOWED_STATUSES = [
  "ON",
  "OFF",
  "DELETED",
] as const;

/*
 * MenuItemFormModal.tsx ke same Menu Type options.
 */
const ALLOWED_MENU_TYPES = [
  "Thalis",
  "Combos",
  "Breakfast",
  "Rice And Biryani",
  "Dal and Subzi",
  "Chicken and Mutton",
  "Roti Paratha",
  "Chinese",
  "Pizza and Sandwiches",
  "Fast Food",
  "Burger",
  "Starters and Snacks",
  "Sweets",
  "Beverages",
  "Restro Specials",
  "Bakery",
] as const;

type ExactHeader = (typeof EXACT_HEADERS)[number];

type MenuStatus =
  (typeof ALLOWED_STATUSES)[number];

type PreparedRow = {
  rowNumber: number;
  itemCode: string;
  autoGenerated: boolean;

  payload: {
    restro_code: number;
    item_code: string;
    item_name: string;
    item_description: string | null;
    item_category: string | null;
    menu_type: string | null;
    item_cuisine: string | null;
    start_time: string | null;
    end_time: string | null;
    restro_price: number;
    base_price: number;
    gst_percent: number;
    base_price_gst: number;
    selling_price: number;
    menu_type_rank: number | null;
    status: MenuStatus;
    menu_item_image: string | null;
    updated_at: string;
  };
};

function cleanText(value: unknown) {
  if (value === undefined || value === null) {
    return "";
  }

  return String(value).trim();
}

function normalizeHeader(value: unknown) {
  return cleanText(value).replace(/^\uFEFF/, "");
}

function isDigitsOnly(value: unknown) {
  return /^\d+$/.test(cleanText(value));
}

function parseRequiredNumber(
  value: unknown,
  rowNumber: number,
  columnName: string,
  errors: string[]
) {
  const raw = cleanText(value);

  if (!raw) {
    errors.push(
      `Row ${rowNumber}: ${columnName} is required`
    );

    return null;
  }

  const normalized = raw.replace(/,/g, "");

  if (!/^(?:\d+|\d*\.\d+)$/.test(normalized)) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be numeric. Received "${raw}"`
    );

    return null;
  }

  const numberValue = Number(normalized);

  if (!Number.isFinite(numberValue)) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be a valid number`
    );

    return null;
  }

  if (numberValue < 0) {
    errors.push(
      `Row ${rowNumber}: ${columnName} cannot be negative`
    );

    return null;
  }

  return numberValue;
}

function parseOptionalWholeNumber(
  value: unknown,
  rowNumber: number,
  columnName: string,
  errors: string[]
) {
  const raw = cleanText(value);

  if (!raw) {
    return null;
  }

  if (!/^\d+$/.test(raw)) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be a whole number. Received "${raw}"`
    );

    return null;
  }

  const numberValue = Number(raw);

  if (
    !Number.isSafeInteger(numberValue) ||
    numberValue < 0
  ) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be a valid whole number`
    );

    return null;
  }

  return numberValue;
}

function parseStatus(
  value: unknown,
  rowNumber: number,
  errors: string[]
): MenuStatus | null {
  const status = cleanText(value).toUpperCase();

  if (!status) {
    errors.push(
      `Row ${rowNumber}: Status is required`
    );

    return null;
  }

  if (
    !ALLOWED_STATUSES.includes(
      status as MenuStatus
    )
  ) {
    errors.push(
      `Row ${rowNumber}: Status must be ON, OFF or DELETED. Received "${cleanText(
        value
      )}"`
    );

    return null;
  }

  return status as MenuStatus;
}

function parseMenuType(
  value: unknown,
  rowNumber: number,
  errors: string[]
) {
  const raw = cleanText(value);

  if (!raw) {
    return null;
  }

  const matched = ALLOWED_MENU_TYPES.find(
    (allowed) =>
      allowed.toLowerCase() === raw.toLowerCase()
  );

  if (!matched) {
    errors.push(
      `Row ${rowNumber}: Invalid Menu Type "${raw}". Allowed values: ${ALLOWED_MENU_TYPES.join(
        ", "
      )}`
    );

    return null;
  }

  return matched;
}

function calculateMenuRank(
  menuType: string | null
) {
  const value = cleanText(
    menuType
  ).toLowerCase();

  if (!value) return null;

  if (value === "breakfast") return 1;
  if (value === "combos") return 2;
  if (value === "thalis") return 3;
  if (value === "rice and biryani") return 4;
  if (value === "dal and subzi") return 5;
  if (value === "chicken and mutton") return 6;
  if (value === "roti paratha") return 7;
  if (value === "chinese") return 8;
  if (value === "pizza and sandwiches") return 9;
  if (value === "fast food") return 10;
  if (value === "burger") return 11;
  if (value === "starters and snacks") return 12;
  if (value === "sweets") return 13;
  if (value === "beverages") return 14;
  if (value === "restro specials") return 15;
  if (value === "bakery") return 16;

  return null;
}

function parseExcelTime(
  value: unknown,
  rowNumber: number,
  columnName: string,
  errors: string[]
) {
  if (
    value === undefined ||
    value === null ||
    cleanText(value) === ""
  ) {
    return null;
  }

  /*
   * Excel time decimal value.
   */
  if (typeof value === "number") {
    if (
      !Number.isFinite(value) ||
      value < 0 ||
      value >= 1
    ) {
      errors.push(
        `Row ${rowNumber}: ${columnName} contains an invalid Excel time`
      );

      return null;
    }

    const totalSeconds = Math.round(
      value * 24 * 60 * 60
    );

    const hours = String(
      Math.floor(totalSeconds / 3600) % 24
    ).padStart(2, "0");

    const minutes = String(
      Math.floor((totalSeconds % 3600) / 60)
    ).padStart(2, "0");

    const seconds = String(
      totalSeconds % 60
    ).padStart(2, "0");

    return `${hours}:${minutes}:${seconds}`;
  }

  const raw = cleanText(value);

  const match = raw.match(
    /^(\d{1,2}):(\d{2})(?::(\d{2}))?$/
  );

  if (!match) {
    errors.push(
      `Row ${rowNumber}: ${columnName} must be HH:MM or HH:MM:SS. Received "${raw}"`
    );

    return null;
  }

  const hours = Number(match[1]);
  const minutes = Number(match[2]);
  const seconds = Number(match[3] ?? "0");

  if (
    hours < 0 ||
    hours > 23 ||
    minutes < 0 ||
    minutes > 59 ||
    seconds < 0 ||
    seconds > 59
  ) {
    errors.push(
      `Row ${rowNumber}: ${columnName} contains an invalid time "${raw}"`
    );

    return null;
  }

  return `${String(hours).padStart(
    2,
    "0"
  )}:${String(minutes).padStart(
    2,
    "0"
  )}:${String(seconds).padStart(2, "0")}`;
}

function validateHeaders(
  actualHeaders: unknown[]
) {
  const normalizedHeaders =
    actualHeaders.map(normalizeHeader);

  const errors: string[] = [];

  if (
    normalizedHeaders.length !==
    EXACT_HEADERS.length
  ) {
    errors.push(
      `Header count is incorrect. Expected ${EXACT_HEADERS.length} headers but found ${normalizedHeaders.length}.`
    );
  }

  const maximumLength = Math.max(
    normalizedHeaders.length,
    EXACT_HEADERS.length
  );

  for (
    let index = 0;
    index < maximumLength;
    index++
  ) {
    const expected = EXACT_HEADERS[index];
    const received = normalizedHeaders[index];

    if (expected !== received) {
      errors.push(
        `Column ${index + 1}: Expected header "${expected ?? "none"}" but found "${received ?? "missing"}".`
      );
    }
  }

  const duplicateHeaders =
    normalizedHeaders.filter(
      (header, index) =>
        header &&
        normalizedHeaders.indexOf(header) !== index
    );

  if (duplicateHeaders.length) {
    errors.push(
      `Duplicate headers found: ${Array.from(
        new Set(duplicateHeaders)
      ).join(", ")}`
    );
  }

  return errors;
}

function createRowObject(
  rowValues: unknown[]
) {
  const row = {} as Record<
    ExactHeader,
    unknown
  >;

  EXACT_HEADERS.forEach(
    (header, index) => {
      row[header] =
        rowValues[index] ?? "";
    }
  );

  return row;
}

function isCompletelyBlankRow(
  rowValues: unknown[]
) {
  return rowValues.every(
    (value) => cleanText(value) === ""
  );
}

export async function POST(req: Request) {
  try {
    const formData = await req.formData();

    const selectedRestroCodeRaw =
      cleanText(formData.get("restroCode"));

    const file = formData.get("file");

    if (
      !isDigitsOnly(selectedRestroCodeRaw)
    ) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Restro Code must contain numbers only",
        },
        { status: 400 }
      );
    }

    const selectedRestroCode = Number(
      selectedRestroCodeRaw
    );

    if (
      !Number.isSafeInteger(
        selectedRestroCode
      ) ||
      selectedRestroCode <= 0
    ) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Valid Restro Code required",
        },
        { status: 400 }
      );
    }

    if (!(file instanceof File)) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Excel or CSV file required",
        },
        { status: 400 }
      );
    }

    const fileName =
      file.name.toLowerCase();

    if (
      !fileName.endsWith(".xlsx") &&
      !fileName.endsWith(".xls") &&
      !fileName.endsWith(".csv")
    ) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Only .xlsx, .xls or .csv file is allowed",
        },
        { status: 400 }
      );
    }

    if (file.size <= 0) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Uploaded file is empty",
        },
        { status: 400 }
      );
    }

    if (file.size > 10 * 1024 * 1024) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Menu file is too large. Maximum allowed size is 10 MB",
        },
        { status: 400 }
      );
    }

    const buffer = Buffer.from(
      await file.arrayBuffer()
    );

    let workbook: XLSX.WorkBook;

    try {
      workbook = XLSX.read(buffer, {
        type: "buffer",
        cellDates: false,
        raw: true,
      });
    } catch {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Unable to read the uploaded Excel/CSV file",
        },
        { status: 400 }
      );
    }

    const sheetName =
      workbook.SheetNames[0];

    if (!sheetName) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Excel sheet not found",
        },
        { status: 400 }
      );
    }

    const sheet =
      workbook.Sheets[sheetName];

    const rawRows =
      XLSX.utils.sheet_to_json<unknown[]>(
        sheet,
        {
          header: 1,
          defval: "",
          raw: true,
          blankrows: false,
        }
      );

    if (!rawRows.length) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Excel file is empty",
        },
        { status: 400 }
      );
    }

    const actualHeaders =
      rawRows[0] ?? [];

    const headerErrors =
      validateHeaders(actualHeaders);

    if (headerErrors.length) {
      return NextResponse.json(
        {
          ok: false,
          error: [
            "Invalid menu file headers.",
            ...headerErrors.slice(0, 20),
            "",
            `Required header order: ${EXACT_HEADERS.join(
              " | "
            )}`,
          ].join("\n"),
        },
        { status: 400 }
      );
    }

    const dataRows = rawRows
      .slice(1)
      .filter(
        (row) =>
          !isCompletelyBlankRow(row)
      );

    if (!dataRows.length) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "No menu rows found in the file",
        },
        { status: 400 }
      );
    }

    /*
     * Existing menu rows pehle load hongi.
     * Inhi se last Item Code calculate hoga.
     */
    const {
      data: existingRows,
      error: existingError,
    } = await supabaseServer
      .from("RestroMenuItems")
      .select("id,item_code")
      .eq(
        "restro_code",
        selectedRestroCode
      );

    if (existingError) {
      return NextResponse.json(
        {
          ok: false,
          error:
            existingError.message,
        },
        { status: 500 }
      );
    }

    const existingByItemCode =
      new Map<string, number>();

    const usedItemCodes =
      new Set<string>();

    let maximumItemCode = 0;

    for (
      const existingRow of existingRows ?? []
    ) {
      const code = cleanText(
        existingRow.item_code
      );

      if (!code) continue;

      usedItemCodes.add(code);

      if (existingRow.id) {
        existingByItemCode.set(
          code,
          Number(existingRow.id)
        );
      }

      if (isDigitsOnly(code)) {
        const numericCode = Number(code);

        if (
          Number.isSafeInteger(
            numericCode
          ) &&
          numericCode > maximumItemCode
        ) {
          maximumItemCode = numericCode;
        }
      }
    }

    /*
     * File me manually diye gaye bade Item Codes ko bhi
     * auto-generation se pehle maximum me include karenge.
     */
    for (
      let index = 0;
      index < dataRows.length;
      index++
    ) {
      const row =
        createRowObject(dataRows[index]);

      const rawItemCode =
        cleanText(row["Item Code"]);

      if (
        rawItemCode &&
        isDigitsOnly(rawItemCode)
      ) {
        const numericCode =
          Number(rawItemCode);

        if (
          Number.isSafeInteger(
            numericCode
          ) &&
          numericCode > maximumItemCode
        ) {
          maximumItemCode = numericCode;
        }
      }
    }

    const validationErrors: string[] = [];
    const preparedRows: PreparedRow[] = [];

    const fileItemCodes =
      new Set<string>();

    let generatedItemCodes = 0;

    /*
     * Pehle complete file validate hogi.
     * Validation ke time koi database write nahi hogi.
     */
    for (
      let index = 0;
      index < dataRows.length;
      index++
    ) {
      const values = dataRows[index];
      const rowNumber = index + 2;
      const row = createRowObject(values);

      const errorsBefore =
        validationErrors.length;

      const rowRestroCodeRaw =
        cleanText(row["Restro Code"]);

      if (!rowRestroCodeRaw) {
        validationErrors.push(
          `Row ${rowNumber}: Restro Code is required`
        );
      } else if (
        !isDigitsOnly(rowRestroCodeRaw)
      ) {
        validationErrors.push(
          `Row ${rowNumber}: Restro Code must be numeric. Received "${rowRestroCodeRaw}"`
        );
      }

      const rowRestroCode =
        Number(rowRestroCodeRaw);

      if (
        rowRestroCodeRaw &&
        isDigitsOnly(rowRestroCodeRaw) &&
        (!Number.isSafeInteger(
          rowRestroCode
        ) ||
          rowRestroCode <= 0)
      ) {
        validationErrors.push(
          `Row ${rowNumber}: Restro Code is invalid`
        );
      }

      if (
        Number.isSafeInteger(
          rowRestroCode
        ) &&
        rowRestroCode > 0 &&
        rowRestroCode !==
          selectedRestroCode
      ) {
        validationErrors.push(
          `Row ${rowNumber}: File Restro Code ${rowRestroCode} does not match selected Restro Code ${selectedRestroCode}`
        );
      }

      let itemCode = cleanText(
        row["Item Code"]
      );

      let autoGenerated = false;

      /*
       * Filled Item Code:
       * numeric hona compulsory hai.
       *
       * Blank Item Code:
       * last existing maximum + 1 se generate hoga.
       */
      if (itemCode) {
        if (!isDigitsOnly(itemCode)) {
          validationErrors.push(
            `Row ${rowNumber}: Item Code must be numeric or blank. Received "${itemCode}"`
          );
        } else {
          const itemCodeNumber =
            Number(itemCode);

          if (
            !Number.isSafeInteger(
              itemCodeNumber
            ) ||
            itemCodeNumber <= 0
          ) {
            validationErrors.push(
              `Row ${rowNumber}: Item Code must be a positive whole number`
            );
          }

          if (
            fileItemCodes.has(itemCode)
          ) {
            validationErrors.push(
              `Row ${rowNumber}: Duplicate Item Code ${itemCode} found in the file`
            );
          } else {
            fileItemCodes.add(itemCode);
          }
        }
      } else {
        do {
          maximumItemCode += 1;
          itemCode = String(
            maximumItemCode
          );
        } while (
          usedItemCodes.has(itemCode) ||
          fileItemCodes.has(itemCode)
        );

        autoGenerated = true;
        generatedItemCodes += 1;

        usedItemCodes.add(itemCode);
        fileItemCodes.add(itemCode);
      }

      const itemName = cleanText(
        row["Item Name"]
      );

      if (!itemName) {
        validationErrors.push(
          `Row ${rowNumber}: Item Name is required`
        );
      }

      const menuType = parseMenuType(
        row["Menu Type"],
        rowNumber,
        validationErrors
      );

      const itemCuisine = cleanText(
        row["Item Cuisine"]
      );

      const startTime = parseExcelTime(
        row["Start Time"],
        rowNumber,
        "Start Time",
        validationErrors
      );

      const endTime = parseExcelTime(
        row["End Time"],
        rowNumber,
        "End Time",
        validationErrors
      );

      const restroPrice =
        parseRequiredNumber(
          row["Restro Price"],
          rowNumber,
          "Restro Price",
          validationErrors
        );

      const basePrice =
        parseRequiredNumber(
          row["Base Price"],
          rowNumber,
          "Base Price",
          validationErrors
        );

      const gstPercent =
        parseRequiredNumber(
          row["GST %"],
          rowNumber,
          "GST %",
          validationErrors
        );

      const basePriceGst =
        parseRequiredNumber(
          row["Base Price GST"],
          rowNumber,
          "Base Price GST",
          validationErrors
        );

      const sellingPrice =
        parseRequiredNumber(
          row["Selling Price"],
          rowNumber,
          "Selling Price",
          validationErrors
        );

      if (
        gstPercent !== null &&
        gstPercent > 100
      ) {
        validationErrors.push(
          `Row ${rowNumber}: GST % cannot be greater than 100`
        );
      }

      const uploadedMenuTypeRank =
        parseOptionalWholeNumber(
          row["Menu Type Rank"],
          rowNumber,
          "Menu Type Rank",
          validationErrors
        );

      const finalMenuTypeRank =
        uploadedMenuTypeRank ??
        calculateMenuRank(menuType);

      const status = parseStatus(
        row["Status"],
        rowNumber,
        validationErrors
      );

      if (
        validationErrors.length >
        errorsBefore
      ) {
        continue;
      }

      if (
        restroPrice === null ||
        basePrice === null ||
        gstPercent === null ||
        basePriceGst === null ||
        sellingPrice === null ||
        status === null
      ) {
        continue;
      }

      preparedRows.push({
        rowNumber,
        itemCode,
        autoGenerated,

        payload: {
          restro_code:
            selectedRestroCode,

          item_code: itemCode,

          item_name: itemName,

          item_description:
            cleanText(
              row["Item Description"]
            ) || null,

          item_category:
            cleanText(
              row["Item Category"]
            ) || null,

          menu_type: menuType,

          item_cuisine:
            itemCuisine || null,

          start_time: startTime,
          end_time: endTime,

          restro_price:
            restroPrice,

          base_price: basePrice,

          gst_percent:
            gstPercent,

          base_price_gst:
            basePriceGst,

          selling_price:
            sellingPrice,

          menu_type_rank:
            finalMenuTypeRank,

          status,

          menu_item_image:
            cleanText(
              row["Menu Item Image"]
            ) || null,

          updated_at:
            new Date().toISOString(),
        },
      });
    }

    /*
     * Ek bhi validation error hua to koi row save nahi hogi.
     */
    if (validationErrors.length) {
      const shownErrors =
        validationErrors.slice(0, 50);

      const remainingErrors =
        validationErrors.length -
        shownErrors.length;

      return NextResponse.json(
        {
          ok: false,

          error: [
            `Menu file validation failed. ${validationErrors.length} error(s) found. No rows were uploaded.`,
            "",
            ...shownErrors,
            ...(remainingErrors > 0
              ? [
                  "",
                  `And ${remainingErrors} more error(s).`,
                ]
              : []),
          ].join("\n"),

          totalRows: dataRows.length,

          validRows:
            preparedRows.length,

          invalidRows:
            dataRows.length -
            preparedRows.length,
        },
        { status: 400 }
      );
    }

    let inserted = 0;
    let updated = 0;

    const databaseErrors: string[] = [];

    for (const preparedRow of preparedRows) {
      const existingId =
        existingByItemCode.get(
          preparedRow.itemCode
        );

      if (existingId) {
        const { error } =
          await supabaseServer
            .from("RestroMenuItems")
            .update(preparedRow.payload)
            .eq("id", existingId)
            .eq(
              "restro_code",
              selectedRestroCode
            );

        if (error) {
          databaseErrors.push(
            `Row ${preparedRow.rowNumber}: ${error.message}`
          );
        } else {
          updated += 1;
        }
      } else {
        const { data, error } =
          await supabaseServer
            .from("RestroMenuItems")
            .insert({
              ...preparedRow.payload,
              created_at:
                new Date().toISOString(),
            })
            .select("id,item_code")
            .single();

        if (error) {
          databaseErrors.push(
            `Row ${preparedRow.rowNumber}: ${error.message}`
          );
        } else {
          inserted += 1;

          if (data?.id) {
            existingByItemCode.set(
              preparedRow.itemCode,
              Number(data.id)
            );
          }
        }
      }
    }

    if (databaseErrors.length) {
      return NextResponse.json(
        {
          ok: false,

          error: [
            "Menu data was valid, but some database rows could not be saved.",
            ...databaseErrors.slice(0, 30),
          ].join("\n"),

          inserted,
          updated,
          failed:
            databaseErrors.length,
        },
        { status: 500 }
      );
    }

    return NextResponse.json({
      ok: true,
      inserted,
      updated,
      generatedItemCodes,
      totalRows: preparedRows.length,

      message: [
        "Menu Upload Successful",
        "",
        `Total Rows: ${preparedRows.length}`,
        `Inserted: ${inserted}`,
        `Updated: ${updated}`,
        `Generated Item Codes: ${generatedItemCodes}`,
      ].join("\n"),
    });
  } catch (error: any) {
    return NextResponse.json(
      {
        ok: false,
        error:
          error?.message ||
          "Menu upload failed",
      },
      { status: 500 }
    );
  }
}
